### PR TITLE
Do not use deprecated gradle internal VersionNumber (Fix Gradle 8.1 deprecation warning)

### PR DESCRIPTION
**Pull request by breskeby**
This fixes caused deprecation warnings and incompatibility with Gradle => 8.1.

### CODE REVIEW

**Comment by breskeby** [comment]
Hey there. 
this is a simple fix for a deprecation warning we see (which results in a build failure in our case) when building elasticsearch with the latest Gradle 8.1 release candidate.

**Review by augi — CHANGES_REQUESTED** [review]
Hello, thank you very much for your contribution! 🙏 

I feel that just copying the original `VersionNumber` brings too much code to be maintained, so I'm thinking about a way how to omit it. For example, what about delegating of most of the methods to `DefaultGradleVersion`? I know this class is in `internal` package, but I would prefer it over copying so huge chunk of code 🙏

**Comment by breskeby** [comment]
Hey @augi 

DefaultGradleVersion is not applicable for general use as it's totally tailored to handling only the gradle version and is not applicable for dealing with general version handling as done here. Let me shrink that VersionNumber class down to the bare minimum of what is required here instead? 
Alternatively, we can use https://ysb33rorg.gitlab.io/grolifant/ which is a convenience library containing classes for Version handling. wdyt?

**Comment by augi** [comment]
Yep, as my objective is to decrease the amount of new code added, shrinking the `VersionNumber` class features to the bare minimum also works for me 👍

**Comment by augi** [comment]
Thank you! 👍 The change is published as `0.16.12`.

**Comment by breskeby** [comment]
thank you!

**Pull request merged**
